services:
  mysql:
    image: mysql:8.0
    container_name: cuboid_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: cuboid_warehouse
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --local-infile=1

volumes:
  mysql_data:
